server:
  port: 8080
  servlet:
    context-path: /palm/bank

spring:
  application:
    name: palm-bank-life-web
  datasource:
    url: jdbc:mysql://localhost:3306/palm-bank?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    redis:
        redisson:
          config: |
            singleServerConfig:
              address: "redis://localhost:6379"
              database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  # 添加这行，支持下划线转驼峰